spring:
  webflux:
    cors:
      allowed-origins:
        - "https://api.example.com"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/pageday
    username: yourusername
    password: yourpassword
    repositories:
      enabled: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: pagedaypage@gmail.com
    password: dylkrqmyaxyzscay
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    io.r2dbc.spi: INFO

snowflake:
  datacenter-id: 1
  worker-id: 1
