spring:
  application:
    name: user-server
  profiles:
    active: local
  mail:
    host: smtp.gmail.com
    port: 587
    username: pagedaypage@gmail.com
    password: dylkrqmyaxyzscay
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

