spring:
  webflux:
    cors:
      allowed-origins:
        - "https://dev.example.com"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/pageday
    username: yourusername
    password: yourpassword
    repositories:
      enabled: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: pagedaypage@gmail.com
    password: dylkrqmyaxyzscay
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework: INFO
    io.r2dbc.spi: INFO

snowflake:
  datacenter-id: 1
  worker-id: 1

jwt:
  access:
    secret-key: 4MC3eE1t4DlQKkY5xGhF8Nb9ysl0VJZROD4edPQbz/4=
    expiration-time: 3600000  # 1 hour
  refresh:
    secret-key: eIMe8mLQGOpZg7Fj24M3FY3Ej0FzQ+S4mAdG4lNGFg0=
    expiration-time: 604800000  # 7 days
